language: node_js

node_js:
  - "10"

sudo: required

services:
  - docker

deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESS_KEY"
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: "us-west-1"
  app: "Travis-final-deployment"
  env: "TravisFinalDeployment-env"
  bucket_name: "elasticbeanstalk-us-west-1-499663575711"
